/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AuthenticationRequest } from '../model/models';
import { AuthenticationResponse } from '../model/models';
import { RegistrationRequest } from '../model/models';
import { ResourceNotFoundDetails } from '../model/models';
import { UpdateUserById400Response } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface AuthenticateRequestParams {
    authenticationRequest: AuthenticationRequest;
}

export interface RegisterRequestParams {
    registrationRequest: RegistrationRequest;
}


export interface AuthenticationServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    authenticate(requestParameters: AuthenticateRequestParams, extraHttpRequestParams?: any): Observable<AuthenticationResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    register(requestParameters: RegisterRequestParams, extraHttpRequestParams?: any): Observable<object>;

}
