/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateCardRequest } from '../model/models';
import { ResourceNotFoundDetails } from '../model/models';
import { Result } from '../model/models';
import { UpdateUserById400Response } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface AddCardRequestParams {
    createCardRequest: CreateCardRequest;
}


export interface CardsControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    addCard(requestParameters: AddCardRequestParams, extraHttpRequestParams?: any): Observable<Result>;

}
