/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateCarRequest } from '../model/models';
import { CreateCarResponse } from '../model/models';
import { GetAllCarResponse } from '../model/models';
import { GetCarByIdResponse } from '../model/models';
import { ResourceNotFoundDetails } from '../model/models';
import { UpdateCarRequest } from '../model/models';
import { UpdateCarResponse } from '../model/models';
import { UpdateUserById400Response } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface AddCarRequestParams {
    createCarRequest: CreateCarRequest;
}

export interface DeleteCarByIdRequestParams {
    id: number;
}

export interface GetCarByIdRequestParams {
    id: number;
}

export interface UpdateCarByIdRequestParams {
    id: number;
    updateCarRequest: UpdateCarRequest;
}


export interface CarsControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    addCar(requestParameters: AddCarRequestParams, extraHttpRequestParams?: any): Observable<CreateCarResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    deleteCarById(requestParameters: DeleteCarByIdRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
*/
    getAllCars(extraHttpRequestParams?: any): Observable<Array<GetAllCarResponse>>;

    /**
     * 
     * 
* @param requestParameters
     */
    getCarById(requestParameters: GetCarByIdRequestParams, extraHttpRequestParams?: any): Observable<GetCarByIdResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    updateCarById(requestParameters: UpdateCarByIdRequestParams, extraHttpRequestParams?: any): Observable<UpdateCarResponse>;

}
