/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateCarRequest } from '../model/models';
import { CreatedCarResponse } from '../model/models';
import { GetAllCarResponse } from '../model/models';
import { UpdateModel400Response } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface Add2RequestParams {
    createCarRequest: CreateCarRequest;
}


export interface CarsControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    add2(requestParameters: Add2RequestParams, extraHttpRequestParams?: any): Observable<CreatedCarResponse>;

    /**
     * 
     * 
*/
    getAll2(extraHttpRequestParams?: any): Observable<Array<GetAllCarResponse>>;

}
