/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateModelRequest } from '../model/models';
import { CreatedModelResponse } from '../model/models';
import { GetAll400Response } from '../model/models';
import { GetAllModelResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface Add1RequestParams {
    createModelRequest: CreateModelRequest;
}


export interface ModelsControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    add1(requestParameters: Add1RequestParams, extraHttpRequestParams?: any): Observable<CreatedModelResponse>;

    /**
     * 
     * 
*/
    getAll1(extraHttpRequestParams?: any): Observable<Array<GetAllModelResponse>>;

}
