/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateRentalRequest } from '../model/models';
import { GetAllRentalResponse } from '../model/models';
import { GetRentalByIdResponse } from '../model/models';
import { ResourceNotFoundDetails } from '../model/models';
import { Result } from '../model/models';
import { UpdateRentalRequest } from '../model/models';
import { UpdateRentalResponse } from '../model/models';
import { UpdateUserById400Response } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface AddRentalRequestParams {
    createRentalRequest: CreateRentalRequest;
}

export interface CheckAvailabilityRequestParams {
    createRentalRequest: CreateRentalRequest;
}

export interface DeleteRentalByIdRequestParams {
    id: number;
}

export interface GetRentalByIdRequestParams {
    id: number;
}

export interface UpdateRentalByIdRequestParams {
    id: number;
    updateRentalRequest: UpdateRentalRequest;
}


export interface RentalsControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    addRental(requestParameters: AddRentalRequestParams, extraHttpRequestParams?: any): Observable<Result>;

    /**
     * 
     * 
* @param requestParameters
     */
    checkAvailability(requestParameters: CheckAvailabilityRequestParams, extraHttpRequestParams?: any): Observable<Result>;

    /**
     * 
     * 
* @param requestParameters
     */
    deleteRentalById(requestParameters: DeleteRentalByIdRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
*/
    getAllRentals(extraHttpRequestParams?: any): Observable<Array<GetAllRentalResponse>>;

    /**
     * 
     * 
* @param requestParameters
     */
    getRentalById(requestParameters: GetRentalByIdRequestParams, extraHttpRequestParams?: any): Observable<GetRentalByIdResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    updateRentalById(requestParameters: UpdateRentalByIdRequestParams, extraHttpRequestParams?: any): Observable<UpdateRentalResponse>;

}
