/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateTransmissionRequest } from '../model/models';
import { CreatedTransmissionResponse } from '../model/models';
import { GetAllTransmissionResponse } from '../model/models';
import { UpdateModel400Response } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface AddRequestParams {
    createTransmissionRequest: CreateTransmissionRequest;
}


export interface TransmissionsControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    add(requestParameters: AddRequestParams, extraHttpRequestParams?: any): Observable<CreatedTransmissionResponse>;

    /**
     * 
     * 
*/
    getAll(extraHttpRequestParams?: any): Observable<Array<GetAllTransmissionResponse>>;

}
