/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateUserRequest } from '../model/models';
import { CreateUserResponse } from '../model/models';
import { GetAllUserResponse } from '../model/models';
import { GetUserByEmailResponse } from '../model/models';
import { GetUserByIdResponse } from '../model/models';
import { ResourceNotFoundDetails } from '../model/models';
import { UpdateUserById400Response } from '../model/models';
import { UpdateUserRequest } from '../model/models';
import { UpdateUserResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface AddUserRequestParams {
    createUserRequest: CreateUserRequest;
}

export interface DeleteUserByIdRequestParams {
    id: number;
}

export interface GetUserByEmailRequestParams {
    email: string;
}

export interface GetUserByIdRequestParams {
    id: number;
}

export interface UpdateUserByIdRequestParams {
    id: number;
    updateUserRequest: UpdateUserRequest;
}


export interface UsersControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    addUser(requestParameters: AddUserRequestParams, extraHttpRequestParams?: any): Observable<CreateUserResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    deleteUserById(requestParameters: DeleteUserByIdRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
*/
    getAllUsers(extraHttpRequestParams?: any): Observable<Array<GetAllUserResponse>>;

    /**
     * 
     * 
* @param requestParameters
     */
    getUserByEmail(requestParameters: GetUserByEmailRequestParams, extraHttpRequestParams?: any): Observable<GetUserByEmailResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    getUserById(requestParameters: GetUserByIdRequestParams, extraHttpRequestParams?: any): Observable<GetUserByIdResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    updateUserById(requestParameters: UpdateUserByIdRequestParams, extraHttpRequestParams?: any): Observable<UpdateUserResponse>;

}
