/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BusinessProblemDetails } from './business-problem-details';
import { ValidationProblemDetails } from './validation-problem-details';


/**
 * @type UpdateUserById400Response
 * @export
 */
export type UpdateUserById400Response = BusinessProblemDetails | ValidationProblemDetails;

